@url = http://127.0.0.1:8888

GET {{url}}/user
Content-Type: application/json

####
POST {{url}}/user
Content-Type: application/json
Accept: application/json

{
    "name":"rohit",
    "email":"r@gmail.com",
    "createdAt":"22-02-2025"
}

####
GET {{url}}/user/1
Content-Type: application/json

####
PATCH {{url}}/user/1
Content-Type: application/json
Accept: application/json

{
    "id":1,
    "name":"rohit",
    "email":"r@gmail.com",
    "createdAt":"22-02-2025"
}

####
DELETE {{url}}/user/1
Content-Type: application/json
Accept: application/json