@url = http://localhost:8888/graphql
 
#### get all users list #####
POST {{url}}
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query {
  users {
    id
    name,
    email
  }
}


#### user view #####
POST {{url}}
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query {
  user(id:15) {
    id
    name,
    email
  }
}

#### user create ######## Create User (Raw GraphQL)
POST {{url}}
# Content-Type: application/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

mutation {
  createUser(input: {
    name: "John Doe",
    email: "user@example.com",
    mobile: "9917404040"
  }) {
    id
    email
    name
  }
}