@url = http://127.0.0.1:8888

####
# @name registerData
POST {{url}}/register
Content-Type: application/json
Accept: application/json

{
    "name":"rohit",
    "mobile":"9077406565",
    "email":"ry@gmail.com",
    "password":"test@123"
}

###
@registerId = {{registerData.response.body.data.id}}

###

GET {{url}}/register
Content-Type: application/json



####
# GET {{url}}/register/{{registerId}}
# Content-Type: application/json

# ####
# PATCH {{url}}/register/{{registerId}}
# Content-Type: application/json
# Accept: application/json

# {
#     "name":"rohit singh",
#     "email":"r@gmail.com"
# }

####
# DELETE {{url}}/register/{{registerId}}
# Content-Type: application/json
# Accept: application/json